# -*- coding: utf-8 -*-
"""dashboard_task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFPvs8DSWuJf0MnUVYasM2lMzfZ8jUAJ
"""

!pip install -q dash plotly pandas

import dash
from dash import dcc, html, Input, Output
import pandas as pd
import plotly.express as px

# ---------------------------------------------------------
# Load Automobile Sales Dataset
# ---------------------------------------------------------

DATA_URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/Data%20Files/historical_automobile_sales.csv"

data = pd.read_csv(DATA_URL)

# ---------------------------------------------------------
# TASK 4.1
# Create Dash application with meaningful title
# ---------------------------------------------------------

app = dash.Dash(__name__)
app.title = "Automobile Statistics Dashboard"

# ---------------------------------------------------------
# Dropdown options
# ---------------------------------------------------------

statistics_options = [
    {
        "label": "Yearly Statistics",
        "value": "Yearly Statistics"
    },
    {
        "label": "Recession Period Statistics",
        "value": "Recession Period Statistics"
    }
]

year_list = sorted(data["Year"].unique().tolist())

# ---------------------------------------------------------
# TASK 4.1 + 4.2 + 4.3
# Dashboard Layout
# ---------------------------------------------------------

app.layout = html.Div([

    html.H1(
        "Automobile Sales Statistics Dashboard",
        style={
            "textAlign": "center",
            "color": "#503D36",
            "fontSize": 24
        }
    ),

    html.P(
        "Select a statistical report type and year.",
        style={
            "textAlign": "center",
            "color": "#503D36",
            "fontSize": 18
        }
    ),

    # TASK 4.2
    html.Div([
        html.Label("Select Statistics:"),

        dcc.Dropdown(
            id="dropdown-statistics",
            options=statistics_options,
            value="Recession Period Statistics",
            placeholder="Select a report type",
            style={
                "width": "80%",
                "padding": "3px",
                "fontSize": 18
            }
        )
    ]),

    html.Br(),

    # Year dropdown
    html.Div([
        html.Label("Select Year:"),

        dcc.Dropdown(
            id="select-year",
            options=[
                {
                    "label": str(year),
                    "value": year
                }
                for year in year_list
            ],
            placeholder="Select a year",
            style={
                "width": "80%",
                "padding": "3px",
                "fontSize": 18
            }
        )
    ]),

    html.Br(),

    # TASK 4.3
    html.Div(
        id="output-container",
        className="chart-grid"
    )
])


# ---------------------------------------------------------
# TASK 4.4
# Callback for input container
# ---------------------------------------------------------

@app.callback(
    Output("select-year", "disabled"),
    Input("dropdown-statistics", "value")
)
def update_input_container(selected_statistics):

    if selected_statistics == "Yearly Statistics":
        return False

    return True


# ---------------------------------------------------------
# TASK 4.4 + TASK 4.5 + TASK 4.6
# Callback for output graphs
# ---------------------------------------------------------

@app.callback(
    Output("output-container", "children"),
    [
        Input("dropdown-statistics", "value"),
        Input("select-year", "value")
    ]
)
def update_output_container(
    selected_statistics,
    input_year
):

    # =====================================================
    # TASK 4.5
    # RECESSION REPORT STATISTICS
    # =====================================================

    if selected_statistics == "Recession Period Statistics":

        recession_data = data[
            data["Recession"] == 1
        ]

        # ---------------------------------------------
        # Graph 1: Automobile Sales during recession
        # ---------------------------------------------

        yearly_recession = (
            recession_data
            .groupby(
                "Year",
                as_index=False
            )["Automobile_Sales"]
            .mean()
        )

        chart1 = dcc.Graph(
            figure=px.line(
                yearly_recession,
                x="Year",
                y="Automobile_Sales",
                title="Average Automobile Sales during Recession"
            )
        )

        # ---------------------------------------------
        # Graph 2: Sales by vehicle type
        # ---------------------------------------------

        vehicle_sales = (
            recession_data
            .groupby(
                "Vehicle_Type",
                as_index=False
            )["Automobile_Sales"]
            .mean()
        )

        chart2 = dcc.Graph(
            figure=px.bar(
                vehicle_sales,
                x="Vehicle_Type",
                y="Automobile_Sales",
                title="Average Automobile Sales by Vehicle Type during Recession"
            )
        )

        # ---------------------------------------------
        # Graph 3: Advertising expenditure
        # ---------------------------------------------

        advertising = (
            recession_data
            .groupby(
                "Vehicle_Type",
                as_index=False
            )["Advertising_Expenditure"]
            .sum()
        )

        chart3 = dcc.Graph(
            figure=px.pie(
                advertising,
                values="Advertising_Expenditure",
                names="Vehicle_Type",
                title="Advertising Expenditure by Vehicle Type during Recession"
            )
        )

        # ---------------------------------------------
        # Graph 4: Unemployment rate and sales
        # ---------------------------------------------

        unemployment = (
            recession_data
            .groupby(
                "Vehicle_Type",
                as_index=False
            )
            .agg(
                unemployment_rate=(
                    "unemployment_rate",
                    "mean"
                ),
                Automobile_Sales=(
                    "Automobile_Sales",
                    "mean"
                )
            )
        )

        chart4 = dcc.Graph(
            figure=px.bar(
                unemployment,
                x="Vehicle_Type",
                y="Automobile_Sales",
                color="unemployment_rate",
                title="Automobile Sales and Unemployment Rate during Recession"
            )
        )

        return [

            html.Div(
                [
                    html.Div(
                        chart1,
                        style={"width": "50%"}
                    ),

                    html.Div(
                        chart2,
                        style={"width": "50%"}
                    )
                ],
                style={
                    "display": "flex"
                }
            ),

            html.Div(
                [
                    html.Div(
                        chart3,
                        style={"width": "50%"}
                    ),

                    html.Div(
                        chart4,
                        style={"width": "50%"}
                    )
                ],
                style={
                    "display": "flex"
                }
            )
        ]


    # =====================================================
    # TASK 4.6
    # YEARLY REPORT STATISTICS
    # =====================================================

    if (
        selected_statistics == "Yearly Statistics"
        and input_year is not None
    ):

        yearly_data = data[
            data["Year"] == input_year
        ]

        # ---------------------------------------------
        # Graph 1: Yearly automobile sales
        # ---------------------------------------------

        yearly_sales = (
            data
            .groupby(
                "Year",
                as_index=False
            )["Automobile_Sales"]
            .sum()
        )

        chart1 = dcc.Graph(
            figure=px.line(
                yearly_sales,
                x="Year",
                y="Automobile_Sales",
                title="Automobile Sales by Year"
            )
        )

        # ---------------------------------------------
        # Graph 2: Monthly sales
        # ---------------------------------------------

        monthly_sales = (
            yearly_data
            .groupby(
                "Month",
                as_index=False
            )["Automobile_Sales"]
            .sum()
        )

        month_order = [
            "Jan", "Feb", "Mar", "Apr",
            "May", "Jun", "Jul", "Aug",
            "Sep", "Oct", "Nov", "Dec"
        ]

        monthly_sales["Month"] = pd.Categorical(
            monthly_sales["Month"],
            categories=month_order,
            ordered=True
        )

        monthly_sales = monthly_sales.sort_values(
            "Month"
        )

        chart2 = dcc.Graph(
            figure=px.line(
                monthly_sales,
                x="Month",
                y="Automobile_Sales",
                title=f"Monthly Automobile Sales in {input_year}"
            )
        )

        # ---------------------------------------------
        # Graph 3: Sales by vehicle type
        # ---------------------------------------------

        vehicle_sales = (
            yearly_data
            .groupby(
                "Vehicle_Type",
                as_index=False
            )["Automobile_Sales"]
            .mean()
        )

        chart3 = dcc.Graph(
            figure=px.bar(
                vehicle_sales,
                x="Vehicle_Type",
                y="Automobile_Sales",
                title=f"Average Automobile Sales by Vehicle Type in {input_year}"
            )
        )

        # ---------------------------------------------
        # Graph 4: Advertising expenditure
        # ---------------------------------------------

        advertising = (
            yearly_data
            .groupby(
                "Vehicle_Type",
                as_index=False
            )["Advertising_Expenditure"]
            .sum()
        )

        chart4 = dcc.Graph(
            figure=px.pie(
                advertising,
                values="Advertising_Expenditure",
                names="Vehicle_Type",
                title=f"Advertising Expenditure by Vehicle Type in {input_year}"
            )
        )

        return [

            html.Div(
                [
                    html.Div(
                        chart1,
                        style={"width": "50%"}
                    ),

                    html.Div(
                        chart2,
                        style={"width": "50%"}
                    )
                ],
                style={
                    "display": "flex"
                }
            ),

            html.Div(
                [
                    html.Div(
                        chart3,
                        style={"width": "50%"}
                    ),

                    html.Div(
                        chart4,
                        style={"width": "50%"}
                    )
                ],
                style={
                    "display": "flex"
                }
            )
        ]

    return None


# ---------------------------------------------------------
# Run application
# ---------------------------------------------------------

if __name__ == "__main__":
    app.run(debug=True)